# SPDX-FileCopyrightText: 2026 ArcheBase
#
# SPDX-License-Identifier: MulanPSL-2.0

{{- if .Values.createNamespace }}
{{- $fullName := include "roboflow.fullname" . }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: roboflow
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- include "roboflow.labels" . | nindent 4 }}
{{- end }}
