name: 'Setup Docker'
description: 'Setup Docker Buildx and pre-pull compose images'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull Docker images
      shell: bash
      run: docker compose pull --quiet
