# SPDX-FileCopyrightText: 2026 ArcheBase
#
# SPDX-License-Identifier: MulanPSL-2.0

"""Type stubs for roboflow._roboflow native module."""

from typing import Optional, List

__version__: str

# =============================================================================
# Main API
# =============================================================================

class Roboflow:
    """Fluent API for robotics data conversion."""

    @staticmethod
    def open(paths: List[str]) -> "Roboflow": ...
    def write_to(self, output: str) -> "Roboflow": ...
    def with_compression(self, preset: "CompressionPreset") -> "Roboflow": ...
    def with_transforms(self, transforms: "TransformBuilder") -> "Roboflow": ...
    def hyper_mode(self) -> "Roboflow": ...
    def run(self) -> "PipelineReport | HyperPipelineReport": ...

class TransformBuilder:
    """Builder for transformation rules."""

    def __init__(self) -> None: ...
    def rename_topic(self, old: str, new: str) -> "TransformBuilder": ...
    def rename_type(self, old: str, new: str) -> "TransformBuilder": ...
    def build(self) -> "TransformBuilder": ...

class CompressionPreset:
    """Compression preset configurations."""

    @staticmethod
    def fast() -> "CompressionPreset": ...
    @staticmethod
    def balanced() -> "CompressionPreset": ...
    @staticmethod
    def slow() -> "CompressionPreset": ...

class PipelineReport:
    """Report from standard pipeline execution."""

    @property
    def files_processed(self) -> int: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def duration_sec(self) -> float: ...
    @property
    def files(self) -> List["FileResult"]: ...

class HyperPipelineReport:
    """Report from hyper pipeline execution."""

    @property
    def files_processed(self) -> int: ...
    @property
    def total_bytes(self) -> int: ...
    @property
    def duration_sec(self) -> float: ...
    @property
    def files(self) -> List["FileResult"]: ...

class FileResult:
    """Result for a single file conversion."""

    @property
    def input_path(self) -> str: ...
    @property
    def output_path(self) -> str: ...
    @property
    def input_bytes(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def messages(self) -> int: ...

class BatchReport:
    """Report from batch processing."""

    @property
    def files_processed(self) -> int: ...
    @property
    def total_bytes(self) -> int: ...

# =============================================================================
# Dataset API
# =============================================================================

class DatasetConfig:
    """Unified dataset configuration for KPS or LeRobot formats."""

    def __init__(
        self,
        format: str,
        *,
        fps: int,
        name: str,
        robot_type: Optional[str] = None,
    ) -> None: ...
    @staticmethod
    def from_file(path: str, format: str = "kps") -> "DatasetConfig": ...
    @staticmethod
    def from_toml(toml_str: str, format: str = "kps") -> "DatasetConfig": ...
    def with_max_frames(self, max_frames: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def fps(self) -> int: ...
    @property
    def robot_type(self) -> Optional[str]: ...
    @property
    def format(self) -> str: ...

class DatasetConverter:
    """Converter for creating ML training datasets."""

    @staticmethod
    def create(output_dir: str, config: DatasetConfig) -> "DatasetConverter": ...
    def convert(self, input_path: str) -> "DatasetStats": ...
    def convert_async(self, input_path: str) -> "ConversionJob": ...

class ConversionJob:
    """Handle for an async conversion job."""

    def is_complete(self) -> bool: ...
    def is_running(self) -> bool: ...
    def cancel(self) -> bool: ...
    def wait(self, timeout: Optional[float] = None) -> Optional["DatasetStats"]: ...
    def wait_with_progress(self) -> Optional["DatasetStats"]: ...
    def get_progress(self) -> Optional["ProgressUpdate"]: ...

class DatasetStats:
    """Statistics from dataset conversion."""

    @property
    def frames_written(self) -> int: ...
    @property
    def images_encoded(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def duration_seconds(self) -> float: ...
    @property
    def warning_count(self) -> int: ...
    @property
    def error_count(self) -> int: ...

class ProgressUpdate:
    """Progress update from conversion job."""

    @property
    def variant_type(self) -> str: ...

def convert(
    input_path: str,
    output_dir: str,
    config: DatasetConfig,
) -> DatasetStats:
    """Synchronous dataset conversion function."""
    ...
