[package]
name = "roboflow-pipeline"
version = "0.2.0"
edition = "2024"
authors = ["Strata Contributors"]
license = "MulanPSL-2.0"
repository = "https://github.com/archebase/roboflow"
description = "Pipeline execution and stages for dataset processing"

[dependencies]
roboflow-core = { workspace = true }
roboflow-executor = { workspace = true }
roboflow-dataset = { workspace = true }
roboflow-media = { workspace = true }
robocodec = { workspace = true }

tracing = "0.1"
async-trait = { workspace = true }

[features]
default = []

[lints]
workspace = true
