# SPDX-FileCopyrightText: 2026 ArcheBase
#
# SPDX-License-Identifier: MulanPSL-2.0

---
apiVersion: v1
kind: Namespace
metadata:
  name: roboflow
  labels:
    name: roboflow
    app.kubernetes.io/part-of: roboflow
    app.kubernetes.io/version: "0.2.0"
