# SPDX-FileCopyrightText: 2026 ArcheBase
#
# SPDX-License-Identifier: MulanPSL-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboflow-worker
  namespace: roboflow
  labels:
    app.kubernetes.io/name: roboflow-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: roboflow
    app.kubernetes.io/version: "0.2.0"
